// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LNTP_thirdweb","status":true,"description":"Integração com Thirdweb para login com carteira","parameters":{}}
];
